### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by itswadesh** [caroso1222/angular2-shop#1]
Hello Caroso,

This is Swadesh (ShopNx). Could not find your email. Hence contacting you this way.
I am working on Javascript e-commerce (ShopNx) http://mshop.codenx.com/

I am really impressed with the ui of your ecommerce app. I thought if you have time together we could make a much better product.

Contact me at admin@codenx.com

**Comment by caroso1222** [comment]
Thanks for reaching out! Feel free to DM me on twitter. https://twitter.com/caroso1222
