### ISSUE TITLE
webpack: Failed to compile.

### ISSUE THREAD

**Issue by saberhamidi** [caroso1222/angular2-shop#2]
Hi Caroso
I tried to run your application after (npm install) however,  I get these bunch of errors; I think the configuration or the packages are not up to date. it will be very helpful if you update this project.

Thanks

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:113:37 
A parameter initializer is only allowed in a function or constructor implementation.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:113:45 
Cannot find name 'keyof'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:113:51 
'=' expected.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:121:45 
A parameter initializer is only allowed in a function or constructor implementation.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:121:55 
Cannot find name 'keyof'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:121:61 
'=' expected.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:137:41 
Cannot find name 'Partial'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:182:21 
Cannot find name 'Partial'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:182:34 
Cannot find name 'Partial'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:551:12 
Invalid use of 'arguments'. Modules are automatically in strict mode.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:614:6 
A computed property name must be of type 'string', 'number', 'symbol', or 'any'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:614:7 
Cannot find name 'k'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:614:12 
Cannot find name 'keyof'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:614:18 
']' expected.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:614:18 
Cannot find name 'T'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:614:19 
';' expected.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:614:20 
Declaration or statement expected.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:614:22 
Cannot find name 'Spy'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:619:23 
Cannot find name 'Spy'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:621:31 
Cannot find name 'Spy'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:623:40 
Cannot find name 'Spy'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:625:32 
Cannot find name 'Spy'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:627:33 
Cannot find name 'Spy'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:629:16 
Cannot find name 'Spy'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:668:36 
Cannot find name 'Reporter'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:674:20 
Cannot find name 'RunDetails'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:678:18 
Cannot find name 'Suite'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:679:32 
Cannot find name 'SuiteOrSpec'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:688:14 
Cannot find name 'Spec'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:689:15 
Cannot find name 'Clock'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:693:29 
Cannot find name 'HtmlReporter'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:694:31 
Cannot find name 'HtmlSpecFilter'.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:697:0 
Declaration or statement expected.

ERROR in [default] /Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index.d.ts:702:25 
Module '"/Users/Saber/Desktop/angular2-shop/node_modules/@types/jasmine/index".jasmine' has no exported member 'Jasmine'.
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  3.09 kB       0       
webpack: Failed to compile.

**Comment by AH72KING** [comment]
You have to update angular cli to latest version also angular-cli.json file to latest version 
flow this [guide line](https://github.com/angular/angular-cli/wiki/stories-1.0-update) 
https://github.com/angular/angular-cli/wiki/stories-1.0-update

**Comment by majormittens** [comment]
I forked and updated to Angular 5 https://github.com/majormittens/angular2-shop

**Comment by caroso1222** [comment]
Thanks for the heads up guys! sorry been away for so long, kinda caught up with work and stuff. I'll the project to the latest Angular 5. Thanks @majormittens for that fork! I'll take a look at that if you mind and pull some of those changes into this project. Thanks @AH72KING for your suggestions as well!

**Comment by caroso1222** [comment]
The project is up to date with Angular 5. See commit here: https://github.com/caroso1222/angular2-shop/commit/527d2d08751ac08c2155ab6007c8e5ee05c12b02. 

Thanks again for opening up the issue!

**Comment by majormittens** [comment]
Sure thing, if you find anything useful. 
I ended up scaffolding a new project with the latest angular cli and copying over the src dir. Saw two bugs I couldn't completely explain:

- overflow: scroll appeared on some elements
- unavailable items gained a larger height, thus breaking the rows

**Comment by caroso1222** [comment]
Thanks for the report @majormittens . I'll check out what's the matter with that overflow thing. The row breaking issue is solved in this last update.
