### ISSUE TITLE
Hi, need little help

### ISSUE THREAD

**Issue by kamleshkatpara** [caroso1222/angular2-shop#5]
Can you help me with this :

[https://stackoverflow.com/questions/49244379/angular-5-checkbox-filter-data](https://stackoverflow.com/questions/49244379/angular-5-checkbox-filter-data)

**Comment by caroso1222** [comment]
Sure thing, I just answered the question in SO: https://stackoverflow.com/a/49291461/3468917 

I'll close this issue and keep the conversation in SO.

**Comment by kamleshkatpara** [comment]
Hi @caroso1222 

I tried this [https://rxjs-demos.stackblitz.io](https://rxjs-demos.stackblitz.io)

I can't all my checked categories within a single array like this: 

{
"categories": ["Travel","Games","Movies"] 
}
